# Prices

## Target prices

### Yahoo Finance

In [2]:
import yfinance as yf
symbol = 'TCB'
ticker = yf.Ticker(f"{symbol}.VN")
price_targets = ticker.analyst_price_targets
price_targets

{'current': 34650.0,
 'high': 48000.0,
 'low': 29100.0,
 'mean': 42385.2,
 'median': 43500.0}

### Investing.io

In [ ]:
import requests
import json
import pandas as pd

symbol = 'HPG'
url = f"https://valueinvesting.io/company/estimates?limit=12&symbol={symbol}.VN"

payload = json.dumps({
  "conditions": "[]",
  "mode": "watchlist",
  "existing_columns": "[]",
  "screener_currency": "",
  "latest_tracking_code": "1",
  "metrics_to_queries": "[\"256\",\"258\",\"260\",\"262\",\"146\",\"146\",\"146\",\"146\",\"146\",\"146\",\"103\",\"103\",\"103\",\"103\",\"103\",\"103\",\"233\",\"233\",\"233\",\"233\",\"233\",\"232\",\"232\",\"232\",\"232\",\"232\",\"237\",\"237\",\"237\",\"237\",\"237\",\"234\",\"234\",\"234\",\"234\",\"234\",\"235\",\"235\",\"235\",\"235\",\"235\",\"238\",\"238\",\"238\",\"238\",\"238\",\"239\",\"239\",\"239\",\"239\",\"239\",\"12\",\"168\",\"299\",\"206\"]",
  "metrics_to_queries_period": "[\"-1\",\"-1\",\"-1\",\"-1\",\"0\",\"FY-1\",\"FY-2\",\"FY-3\",\"FY-4\",\"FY-5\",\"0\",\"FY-1\",\"FY-2\",\"FY-3\",\"FY-4\",\"FY-5\",\"FY+1\",\"FY+2\",\"FY+3\",\"FY+4\",\"FY+5\",\"FY+1\",\"FY+2\",\"FY+3\",\"FY+4\",\"FY+5\",\"FY+1\",\"FY+2\",\"FY+3\",\"FY+4\",\"FY+5\",\"FY+1\",\"FY+2\",\"FY+3\",\"FY+4\",\"FY+5\",\"FY+1\",\"FY+2\",\"FY+3\",\"FY+4\",\"FY+5\",\"FY+1\",\"FY+2\",\"FY+3\",\"FY+4\",\"FY+5\",\"FY+1\",\"FY+2\",\"FY+3\",\"FY+4\",\"FY+5\",\"-1\",\"-1\",\"-1\",\"-1\"]",
  "metrics_to_queries_currency_type": "[\"2\",\"2\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"0\",\"0\",\"0\",\"2\"]",
  "filter_default_freq": "[]",
  "filter_metrics": "[]",
  "filter_currency_type": "[]",
  "metrics_financials_grouping": "[\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\",\"NF\"]",
  "metrics_which_latest_days": "[\"None\",\"None\",\"None\",\"None\",\"None\",\"FY\",\"FY\",\"FY\",\"FY\",\"FY\",\"None\",\"FY\",\"FY\",\"FY\",\"FY\",\"FY\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"analystEstimateAnnual\",\"None\",\"None\",\"None\",\"None\"]",
  "name_of_considered_screener": "",
  "ticker_str": "(('HPG', 'VN'))",
  "original_filters": "[]",
  "original_columns": "[{\"field_code\":\"256\"},{\"field_code\":\"258\"},{\"field_code\":\"260\"},{\"field_code\":\"262\"},{\"field_code\":\"146\",\"period\":\"FY@6\"},{\"field_code\":\"103\",\"period\":\"FY@6\"},{\"field_code\":\"233\",\"period\":\"FY+1\"},{\"field_code\":\"233\",\"period\":\"FY+2\"},{\"field_code\":\"233\",\"period\":\"FY+3\"},{\"field_code\":\"233\",\"period\":\"FY+4\"},{\"field_code\":\"233\",\"period\":\"FY+5\"},{\"field_code\":\"232\",\"period\":\"FY+1\"},{\"field_code\":\"232\",\"period\":\"FY+2\"},{\"field_code\":\"232\",\"period\":\"FY+3\"},{\"field_code\":\"232\",\"period\":\"FY+4\"},{\"field_code\":\"232\",\"period\":\"FY+5\"},{\"field_code\":\"237\",\"period\":\"FY+1\"},{\"field_code\":\"237\",\"period\":\"FY+2\"},{\"field_code\":\"237\",\"period\":\"FY+3\"},{\"field_code\":\"237\",\"period\":\"FY+4\"},{\"field_code\":\"237\",\"period\":\"FY+5\"},{\"field_code\":\"234\",\"period\":\"FY+1\"},{\"field_code\":\"234\",\"period\":\"FY+2\"},{\"field_code\":\"234\",\"period\":\"FY+3\"},{\"field_code\":\"234\",\"period\":\"FY+4\"},{\"field_code\":\"234\",\"period\":\"FY+5\"},{\"field_code\":\"235\",\"period\":\"FY+1\"},{\"field_code\":\"235\",\"period\":\"FY+2\"},{\"field_code\":\"235\",\"period\":\"FY+3\"},{\"field_code\":\"235\",\"period\":\"FY+4\"},{\"field_code\":\"235\",\"period\":\"FY+5\"},{\"field_code\":\"238\",\"period\":\"FY+1\"},{\"field_code\":\"238\",\"period\":\"FY+2\"},{\"field_code\":\"238\",\"period\":\"FY+3\"},{\"field_code\":\"238\",\"period\":\"FY+4\"},{\"field_code\":\"238\",\"period\":\"FY+5\"},{\"field_code\":\"239\",\"period\":\"FY+1\"},{\"field_code\":\"239\",\"period\":\"FY+2\"},{\"field_code\":\"239\",\"period\":\"FY+3\"},{\"field_code\":\"239\",\"period\":\"FY+4\"},{\"field_code\":\"239\",\"period\":\"FY+5\"},{\"field_code\":\"12\"},{\"field_code\":\"168\"},{\"field_code\":\"299\"},{\"field_code\":\"206\"}]",
  "original_currency": "[\"\",\"\"]",
  "count_arr": "[]"
})
headers = {
  'accept': 'application/json',
  'accept-language': 'en-US,en;q=0.9,vi;q=0.8,ko;q=0.7,fr;q=0.6,zh-TW;q=0.5,zh;q=0.4',
  'content-type': 'application/json',
  'origin': 'https://valueinvesting.io',
  'priority': 'u=1, i',
  'sec-ch-ua': '"Opera GX";v="127", "Chromium";v="143", "Not A(Brand";v="24"',
  'sec-ch-ua-arch': '"x86"',
  'sec-ch-ua-bitness': '"64"',
  'sec-ch-ua-full-version': '"127.0.5778.75"',
  'sec-ch-ua-full-version-list': '"Opera GX";v="127.0.5778.75", "Chromium";v="143.0.7499.194", "Not A(Brand";v="24.0.0.0"',
  'sec-ch-ua-mobile': '?0',
  'sec-ch-ua-model': '""',
  'sec-ch-ua-platform': '"Windows"',
  'sec-ch-ua-platform-version': '"10.0.0"',
  'sec-fetch-dest': 'empty',
  'sec-fetch-mode': 'cors',
  'sec-fetch-site': 'same-origin',
  'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36 OPR/127.0.0.0 (Edition globalgames-sd)',
  'Cookie': 'beegosessionID=c8d83cd290a878b2ef8edd8948f9667c; cf_clearance=aHgdqJ9DYvPpXFxZJi0vdiZglkvWjN9ivXJt3ZV49ME-1772535795-1.2.1.1-UySGf.5p_WYS6107qYFn5PWfppro9DkJ8uIKHqIqVqjy7lbiJLdsJRK7o1ExAd4lJH8qVSXbPVgBwkcz_VjfSdDrpJIDHcNz6TgM9GuO2cC4xEwbBcaRbjLVH6hzJarEIVNQuHts54q6uK38uKZY949QcVpPJc0b4h__YILNRultG8c1sTAbZDPDf9ud3aG7NN7i_pCOuUZV5skMtbyzBxWvLl8.jB6caY5XhEDgtx0; essay=eEXPcXslkD; _ga=GA1.1.2012916349.1772535797; twk_idm_key=m3rv0sT3N-Z878nry1I_8; TawkConnectionTime=0; twk_uuid_611c4284d6e7610a49b0ad9d=%7B%22uuid%22%3A%221.92R2xxtoQpimRheYQeUvZHdi6ymGX7CtAyweqbdOBtfXIbFEGHMcDDCQcEJIrsQRAqLq77c2yZijQgeKfqUvOjUGtDt4A0gJC3sNCEqLTzJSyzc8EfC2swVrPv10%22%2C%22version%22%3A3%2C%22domain%22%3A%22valueinvesting.io%22%2C%22ts%22%3A1772535801947%7D; token=d6jc01jaiij57r13levg; email=huunhon5597@gmail.com; _ga_4KHY6KT2C0=GS2.1.s1772535796$o1$g1$t1772537684$j6$l0$h0; email=huunhon5597@gmail.com'
}

response = requests.request("POST", url, headers=headers, data=payload)
response = response.json()
response = response['from_ar']['main']
df = pd.DataFrame(response)
df = df.transpose()
price_target_high = df['256_-1']
price_target_low = df['258_-1']
price_target_mean = df['260_-1']
price_target_median = df['262_-1']

HPG.VN    43890
Name: 256_-1, dtype: object

In [16]:
df

            103_0  ... 39_-1
HPG.VN  2012.9171  ...     1

[1 rows x 45 columns]

## Fair price

In [ ]:
import pandas as pd
import requests
import json
symbol = 'SSI'
url = f"https://valueinvesting.io/company/intrinsic_metric?ticker={symbol}.VN"

payload = {}
headers = {
  'accept': '*/*',
  'accept-language': 'en-US,en;q=0.9,vi;q=0.8,ko;q=0.7,fr;q=0.6,zh-TW;q=0.5,zh;q=0.4',
  'content-type': 'application/x-www-form-urlencoded',
  'priority': 'u=1, i',
  'referer': 'https://valueinvesting.io/HPG.VN/valuation/intrinsic-value',
  'sec-ch-ua': '"Opera GX";v="127", "Chromium";v="143", "Not A(Brand";v="24"',
  'sec-ch-ua-arch': '"x86"',
  'sec-ch-ua-bitness': '"64"',
  'sec-ch-ua-full-version': '"127.0.5778.75"',
  'sec-ch-ua-full-version-list': '"Opera GX";v="127.0.5778.75", "Chromium";v="143.0.7499.194", "Not A(Brand";v="24.0.0.0"',
  'sec-ch-ua-mobile': '?0',
  'sec-ch-ua-model': '""',
  'sec-ch-ua-platform': '"Windows"',
  'sec-ch-ua-platform-version': '"10.0.0"',
  'sec-fetch-dest': 'empty',
  'sec-fetch-mode': 'cors',
  'sec-fetch-site': 'same-origin',
  'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36 OPR/127.0.0.0 (Edition globalgames-sd)',
  'Cookie': 'beegosessionID=c8d83cd290a878b2ef8edd8948f9667c; cf_clearance=aHgdqJ9DYvPpXFxZJi0vdiZglkvWjN9ivXJt3ZV49ME-1772535795-1.2.1.1-UySGf.5p_WYS6107qYFn5PWfppro9DkJ8uIKHqIqVqjy7lbiJLdsJRK7o1ExAd4lJH8qVSXbPVgBwkcz_VjfSdDrpJIDHcNz6TgM9GuO2cC4xEwbBcaRbjLVH6hzJarEIVNQuHts54q6uK38uKZY949QcVpPJc0b4h__YILNRultG8c1sTAbZDPDf9ud3aG7NN7i_pCOuUZV5skMtbyzBxWvLl8.jB6caY5XhEDgtx0; essay=eEXPcXslkD; _ga=GA1.1.2012916349.1772535797; twk_idm_key=m3rv0sT3N-Z878nry1I_8; TawkConnectionTime=0; twk_uuid_611c4284d6e7610a49b0ad9d=%7B%22uuid%22%3A%221.92R2xxtoQpimRheYQeUvZHdi6ymGX7CtAyweqbdOBtfXIbFEGHMcDDCQcEJIrsQRAqLq77c2yZijQgeKfqUvOjUGtDt4A0gJC3sNCEqLTzJSyzc8EfC2swVrPv10%22%2C%22version%22%3A3%2C%22domain%22%3A%22valueinvesting.io%22%2C%22ts%22%3A1772535801947%7D; token=d6jc01jaiij57r13levg; email=huunhon5597@gmail.com; _ga_4KHY6KT2C0=GS2.1.s1772535796$o1$g1$t1772536202$j27$l0$h0; email=huunhon5597@gmail.com'
}

response = requests.request("GET", url, headers=headers, data=payload)
response = response.json()

df = pd.DataFrame(response['data'])
df
# Lấy giá trị cột value_numerical ứng với giá trị "fair_price_5" của cột "value_field"
# fair_price = df[df['value_field'] == 'fair_price_5']['value_numerical'].iloc[0]

,tickers,value_field,value_numerical,value_text
0,SSI.VN,avg_cod,0.04257199,None
1,SSI.VN,avg_coe,0.13766296,None
2,SSI.VN,avg_ddm_fair_price_stable,11857.412,None
3,SSI.VN,avg_epv_fair_price,2262.2056,None
4,SSI.VN,avg_tax,0.19529296,None
...,...,...,...,...
59,SSI.VN,totalDebt/totalEquityAnnual,0.74538076,None
60,SSI.VN,trailing_pe,19.322893,None
61,SSI.VN,volume,26.13523,None
62,SSI.VN,wacc_to_json,None,"{""R1"": [""Category"", ""Low"", ""High""], ""R2"": [""Lo..."
63,SSI.VN,working_cap_to_json,None,"{""R1"": [""(VND in millions except days)"", ""Proj..."

In [23]:
fair_price

'-70755.766'

# Investor type

In [35]:
import pandas as pd
import datetime

# Khởi tạo dataframe rỗng để lưu trữ tất cả dữ liệu
all_data = pd.DataFrame()

# Bắt đầu từ trang 1
page = 1

while True:
    # Tạo URL với số trang hiện tại
    start_date = '2025-01-02'
    end_date = datetime.date.today().strftime('%Y-%m-%d')
    start_date_formatted = datetime.datetime.strptime(start_date, '%Y-%m-%d').date().strftime('%d/%m/%Y')
    end_date_formatted = datetime.datetime.strptime(end_date, '%Y-%m-%d').date().strftime('%d/%m/%Y')

    url = f'https://dulieu.nguoiquansat.vn/History/PhanLoaiNDTHistory?page={page}&fromDate={start_date_formatted}&toDate={end_date_formatted}&exId=&code=VN-Index&idNganh=&_=1769924091168'
    
    try:
        # Đọc dữ liệu từ URL
        table = pd.read_html(url, encoding='utf-8')
        df = pd.DataFrame(table[0])
        
        # Kiểm tra nếu dataframe rỗng thì thoát vòng lặp
        if df.empty:
            print(f"Không có dữ liệu ở trang {page}. Dừng vòng lặp.")
            break
        
        # Ghép dataframe mới vào dataframe tổng
        all_data = pd.concat([all_data, df], ignore_index=True)
        # print(f"Đã lấy dữ liệu từ trang {page}. Tổng số dòng: {len(all_data)}")
        
        # Tăng số trang lên
        page += 1
        
    except Exception as e:
        print(f"Lỗi khi lấy dữ liệu từ trang {page}: {e}")
        break

# print(f"Hoàn thành! Tổng số dòng dữ liệu: {len(all_data)}")
# print(all_data.head())

# Nếu bạn muốn thêm độ trễ giữa các lần request để tránh bị chặn:

# import time

# # Khởi tạo dataframe rỗng
# all_data = pd.DataFrame()
# page = 1

# while True:
#     url = f'https://dulieu.nguoiquansat.vn/History/PhanLoaiNDTHistory?page={page}&fromDate={start_date_formatted}&toDate={end_date_formatted}&exId=&code=VN-Index&idNganh=&_=1769924091168'
    
#     try:
#         table = pd.read_html(url, encoding='utf-8')
#         df = pd.DataFrame(table[0])
        
#         if df.empty:
#             print(f"Không có dữ liệu ở trang {page}. Dừng vòng lặp.")
#             break
        
#         all_data = pd.concat([all_data, df], ignore_index=True)
#         print(f"Đã lấy dữ liệu từ trang {page}. Tổng số dòng: {len(all_data)}")
        
#         page += 1
        
#         # Đợi 1 giây trước khi request tiếp theo
#         time.sleep(1)
        
#     except Exception as e:
#         print(f"Lỗi khi lấy dữ liệu từ trang {page}: {e}")
#         break

# print(f"Hoàn thành! Tổng số dòng dữ liệu: {len(all_data)}")

Không có dữ liệu ở trang 19. Dừng vòng lặp.

In [36]:
all_data.columns

MultiIndex([(                    'STT',            'STT'),
            (                   'Ngày',           'Ngày'),
            (                  'Mã CK',          'Mã CK'),
            (           'Giá đóng cửa',   'Giá đóng cửa'),
            (          'Tự doanh ròng', 'GTGD khớp lệnh'),
            (          'Tự doanh ròng',      'Tổng GTGD'),
            ('Cá nhân trong nước ròng', 'GTGD khớp lệnh'),
            ('Cá nhân trong nước ròng',      'Tổng GTGD'),
            ('Tổ chức trong nước ròng', 'GTGD khớp lệnh'),
            ('Tổ chức trong nước ròng',      'Tổng GTGD'),
            ('Cá nhân nước ngoài ròng', 'GTGD khớp lệnh'),
            ('Cá nhân nước ngoài ròng',      'Tổng GTGD'),
            ('Tổ chức nước ngoài ròng', 'GTGD khớp lệnh'),
            ('Tổ chức nước ngoài ròng',      'Tổng GTGD')],
           )

In [37]:
# Xóa các cột có level 1 là 'GTGD khớp lệnh'
cols_to_drop = [col for col in all_data.columns if col[1] == 'GTGD khớp lệnh']
all_data = all_data.drop(columns=cols_to_drop)

# Kiểm tra kết quả
print("Các cột còn lại sau khi xóa 'GTGD khớp lệnh':")
for col in all_data.columns:
    print(f"  Level 0: '{col[0]}' | Level 1: '{col[1]}'")

Các cột còn lại sau khi xóa 'GTGD khớp lệnh':
  Level 0: 'STT' | Level 1: 'STT'
  Level 0: 'Ngày' | Level 1: 'Ngày'
  Level 0: 'Mã CK' | Level 1: 'Mã CK'
  Level 0: 'Giá đóng cửa' | Level 1: 'Giá đóng cửa'
  Level 0: 'Tự doanh ròng' | Level 1: 'Tổng GTGD'
  Level 0: 'Cá nhân trong nước ròng' | Level 1: 'Tổng GTGD'
  Level 0: 'Tổ chức trong nước ròng' | Level 1: 'Tổng GTGD'
  Level 0: 'Cá nhân nước ngoài ròng' | Level 1: 'Tổng GTGD'
  Level 0: 'Tổ chức nước ngoài ròng' | Level 1: 'Tổng GTGD'

In [38]:
# Xử lý multi-level index columns
all_data.columns = [
    col[0] if col[0] == col[1] else f"{col[0]} {col[1]}"
    for col in all_data.columns
]

# Kiểm tra kết quả
print("Các cột sau khi xử lý:")
print(all_data.columns.tolist())
print(f"\nSố cột: {len(all_data.columns)}")
print("\n5 dòng đầu tiên:")
print(all_data.head())

Các cột sau khi xử lý:
['STT', 'Ngày', 'Mã CK', 'Giá đóng cửa', 'Tự doanh ròng Tổng GTGD', 'Cá nhân trong nước ròng Tổng GTGD', 'Tổ chức trong nước ròng Tổng GTGD', 'Cá nhân nước ngoài ròng Tổng GTGD', 'Tổ chức nước ngoài ròng Tổng GTGD']

Số cột: 9

5 dòng đầu tiên:
   STT        Ngày     Mã CK  Giá đóng cửa  Tự doanh ròng Tổng GTGD  \
0    1  30/01/2026  VN-Index       1829.04                   187.29
1    2  29/01/2026  VN-Index       1814.98                    52.68
2    3  28/01/2026  VN-Index       1802.91                   118.93
3    4  27/01/2026  VN-Index       1830.50                   639.08
4    5  26/01/2026  VN-Index       1843.72                   350.28

   Cá nhân trong nước ròng Tổng GTGD  Tổ chức trong nước ròng Tổng GTGD  \
0                            -707.95                            -164.40
1                            -277.17                             681.63
2                             437.54                            1230.81
3                            -296.64                            -232.67
4                           -1161.94                             702.11

   Cá nhân nước ngoài ròng Tổng GTGD  Tổ chức nước ngoài ròng Tổng GTGD
0                             257.85                             427.21
1                             190.01                            -647.16
2                            2410.95                           -4198.22
3                            -285.68                             175.90
4                             -94.27                             203.82

In [40]:
# Bỏ cột 'STT'
if 'STT' in all_data.columns:
    all_data = all_data.drop(columns=['STT'])

# Xóa đoạn chữ 'Tổng GTGD' khỏi tên các cột (xử lý cả có/không có khoảng trắng)
all_data.columns = all_data.columns.str.replace('Tổng GTGD', '', regex=False)

# Xóa khoảng trắng thừa ở đầu/cuối tên cột
all_data.columns = all_data.columns.str.strip()

# Kiểm tra kết quả
print("Các cột sau khi xử lý:")
print(all_data.columns.tolist())
print(f"\nSố cột: {len(all_data.columns)}")
print("\n5 dòng đầu tiên:")
print(all_data.head())

Các cột sau khi xử lý:
['Ngày', 'Mã CK', 'Giá đóng cửa', 'Tự doanh ròng', 'Cá nhân trong nước ròng', 'Tổ chức trong nước ròng', 'Cá nhân nước ngoài ròng', 'Tổ chức nước ngoài ròng']

Số cột: 8

5 dòng đầu tiên:
         Ngày     Mã CK  Giá đóng cửa  Tự doanh ròng  Cá nhân trong nước ròng  \
0  30/01/2026  VN-Index       1829.04         187.29                  -707.95
1  29/01/2026  VN-Index       1814.98          52.68                  -277.17
2  28/01/2026  VN-Index       1802.91         118.93                   437.54
3  27/01/2026  VN-Index       1830.50         639.08                  -296.64
4  26/01/2026  VN-Index       1843.72         350.28                 -1161.94

   Tổ chức trong nước ròng  Cá nhân nước ngoài ròng  Tổ chức nước ngoài ròng
0                  -164.40                   257.85                   427.21
1                   681.63                   190.01                  -647.16
2                  1230.81                  2410.95                 -4198.22
3                  -232.67                  -285.68                   175.90
4                   702.11                   -94.27                   203.82

In [41]:
# Chuyển đổi cột 'Ngày' sang định dạng datetime
all_data['Ngày'] = pd.to_datetime(all_data['Ngày'], format='%d/%m/%Y')

# Sắp xếp dataframe theo cột 'Ngày' tăng dần
all_data = all_data.sort_values('Ngày')

# Reset index sau khi sắp xếp
all_data = all_data.reset_index(drop=True)

# Kiểm tra kết quả
print("Các cột sau khi xử lý:")
print(all_data.columns.tolist())
print(f"\nSố dòng: {len(all_data)}")
print("\n5 dòng đầu tiên:")
print(all_data.head())
print("\n5 dòng cuối cùng:")
print(all_data.tail())

Các cột sau khi xử lý:
['Ngày', 'Mã CK', 'Giá đóng cửa', 'Tự doanh ròng', 'Cá nhân trong nước ròng', 'Tổ chức trong nước ròng', 'Cá nhân nước ngoài ròng', 'Tổ chức nước ngoài ròng']

Số dòng: 266

5 dòng đầu tiên:
        Ngày     Mã CK  Giá đóng cửa  Tự doanh ròng  Cá nhân trong nước ròng  \
0 2025-01-02  VN-Index       1269.71        -765.77                  1248.68
1 2025-01-03  VN-Index       1254.59        -991.42                  1555.37
2 2025-01-06  VN-Index       1246.35         289.52                  -705.95
3 2025-01-07  VN-Index       1246.95        -163.47                     7.88
4 2025-01-08  VN-Index       1251.02         455.90                  -516.48

   Tổ chức trong nước ròng  Cá nhân nước ngoài ròng  Tổ chức nước ngoài ròng
0                  -386.22                    17.85                  -114.53
1                   171.51                    14.01                  -749.47
2                   303.30                     3.54                   109.60
3                   247.58                    -8.20                   -83.79
4                   505.25                    -7.39                  -437.28

5 dòng cuối cùng:
          Ngày     Mã CK  Giá đóng cửa  Tự doanh ròng  \
261 2026-01-26  VN-Index       1843.72         350.28
262 2026-01-27  VN-Index       1830.50         639.08
263 2026-01-28  VN-Index       1802.91         118.93
264 2026-01-29  VN-Index       1814.98          52.68
265 2026-01-30  VN-Index       1829.04         187.29

     Cá nhân trong nước ròng  Tổ chức trong nước ròng  \
261                 -1161.94                   702.11
262                  -296.64                  -232.67
263                   437.54                  1230.81
264                  -277.17                   681.63
265                  -707.95                  -164.40

     Cá nhân nước ngoài ròng  Tổ chức nước ngoài ròng
261                   -94.27                   203.82
262                  -285.68                   175.90
263                  2410.95                 -4198.22
264                   190.01                  -647.16
265                   257.85                   427.21

In [42]:
def investor_type(symbol='VN-Index', start_date=None, end_date=None):
    """
    Hàm lấy dữ liệu phân loại nhà đầu tư từ nguoiquansat.vn
    
    Parameters:
    - symbol (str): Mã chứng khoán, mặc định là 'VN-Index'
    - start_date (str): Ngày bắt đầu (định dạng yyyy-mm-dd)
    - end_date (str): Ngày kết thúc (định dạng yyyy-mm-dd), mặc định là ngày hiện tại
    
    Returns:
    - DataFrame: DataFrame chứa dữ liệu phân loại nhà đầu tư đã được xử lý
    """
    import pandas as pd
    import datetime
    
    # Xử lý ngày kết thúc
    if end_date is None:
        end_date = datetime.date.today().strftime('%Y-%m-%d')
    
    # Định dạng lại ngày cho URL
    start_date_formatted = datetime.datetime.strptime(start_date, '%Y-%m-%d').date().strftime('%d/%m/%Y')
    end_date_formatted = datetime.datetime.strptime(end_date, '%Y-%m-%d').date().strftime('%d/%m/%Y')
    
    # Khởi tạo dataframe rỗng
    all_data = pd.DataFrame()
    page = 1
    
    while True:
        # Tạo URL với số trang hiện tại
        url = f'https://dulieu.nguoiquansat.vn/History/PhanLoaiNDTHistory?page={page}&fromDate={start_date_formatted}&toDate={end_date_formatted}&exId=&code={symbol}&idNganh=&_=1769924091168'
        
        try:
            # Đọc dữ liệu từ URL
            table = pd.read_html(url, encoding='utf-8')
            df = pd.DataFrame(table[0])
            
            # Kiểm tra nếu dataframe rỗng thì thoát vòng lặp
            if df.empty:
                break
            
            # Ghép dataframe mới vào dataframe tổng
            all_data = pd.concat([all_data, df], ignore_index=True)
            
            # Tăng số trang lên
            page += 1
            
        except Exception as e:
            print(f"Lỗi khi lấy dữ liệu từ trang {page}: {e}")
            break
    
    # Xử lý dataframe
    # 1. Xóa các cột có level 1 là 'GTGD khớp lệnh'
    if isinstance(all_data.columns, pd.MultiIndex):
        cols_to_drop = [col for col in all_data.columns if col[1] == 'GTGD khớp lệnh']
        all_data = all_data.drop(columns=cols_to_drop)
        
        # 2. Xử lý multi-level index columns
        all_data.columns = [
            col[0] if col[0] == col[1] else f"{col[0]} {col[1]}"
            for col in all_data.columns
        ]
    
    # 3. Bỏ cột 'STT'
    if 'STT' in all_data.columns:
        all_data = all_data.drop(columns=['STT'])
    
    # 4. Xóa đoạn chữ 'Tổng GTGD' khỏi tên các cột
    all_data.columns = all_data.columns.str.replace('Tổng GTGD', '', regex=False)
    all_data.columns = all_data.columns.str.strip()
    
    # 5. Chuyển đổi cột 'Ngày' sang định dạng datetime và sắp xếp
    all_data['Ngày'] = pd.to_datetime(all_data['Ngày'], format='%d/%m/%Y')
    all_data = all_data.sort_values('Ngày')
    all_data = all_data.reset_index(drop=True)
    
    return all_data

In [ ]:
# Sử dụng với tham số mặc định (VN-Index, ngày hiện tại)
# df = investor_type(start_date='2025-01-02')
# print(df.head())

# Sử dụng với tham số tùy chỉnh
# df = investor_type(symbol='HPG', start_date='2024-01-01', end_date='2024-12-31')
# print(df.head())

        Ngày Mã CK  Giá đóng cửa  Tự doanh ròng  Cá nhân trong nước ròng  \
0 2024-09-17   HPG         25.25          -2.97                    46.09
1 2024-09-18   HPG         25.10          -6.25                    85.82
2 2024-09-19   HPG         25.25           5.16                    71.25
3 2024-09-20   HPG         25.65        -144.72                   222.25
4 2024-09-23   HPG         25.70         -85.18                    67.15

   Tổ chức trong nước ròng  Cá nhân nước ngoài ròng  Tổ chức nước ngoài ròng
0                   -34.39                     0.51                    -9.23
1                     7.63                    -6.53                   -80.66
2                    -1.52                    -0.15                   -74.74
3                    -8.27                     1.12                   -70.38
4                    17.90                     5.95                    -5.81